```{r}
library(hexbin)
library(ggplot2)
library(roahd)
library("fdatest")
library(spatstat.geom)
```

# load and preprocess the data

```{r}
data_numeric_cleaned = readRDS("../../data/data_numeric_cleaned2.RData")
survey_data = readRDS("../../data/Surveycleaned.RData")
test<-survey_data$campo.studi!="STEM (Science, Technology, Engineering, Mathematics)"         
survey_data$campo.studi<-ifelse(test,"Others","STEM (Science, Technology, Engineering, Mathematics)")
survey_data$campo.studi[is.na(survey_data$campo.studi)] = "missing"
###########
test<-survey_data$stato!="Italia"         
survey_data$stato<-ifelse(test,"Others","Italia")
survey_data$stato[is.na(survey_data$stato)] = "missing"
###########
test<-survey_data$libri!="0"         
survey_data$libri<-ifelse(test,"1+","0")
survey_data$libri[is.na(survey_data$libri)] = "missing"
##########
test<-survey_data$estero!="No"         
survey_data$estero<-ifelse(test,"Si","No")
survey_data$estero[is.na(survey_data$estero)] = "missing"
##########
colnames(survey_data)[1] = "age"

test<-survey_data$age < 22.5         
survey_data$age<-ifelse(test,"Under22.5","Over22.5")
survey_data$age[is.na(survey_data$age)] = "missing"
######### TO DO
# test<-survey_data$genere!="No"         
# survey_data$genere<-ifelse(test,"Si","No")
# survey_data$genere[is.na(survey_data$genere)] = "missing"
######### 
test<-survey_data$concerti>5         
survey_data$concerti<-ifelse(test,"more than 5","less than 5")
######### 
survey_data$regione[is.na(survey_data$regione)] = "missing"
######### TO DO
survey_data$abitanti.citta[survey_data$abitanti.citta=="Meno di 1000 abitanti"] = "Tra 10.000 e 100.000"
# Rimuovi livelli vuoti
survey_data$abitanti.citta <- droplevels(survey_data$abitanti.citta)


```

# combine the data

```{r}
combined_data <- merge(data_numeric_cleaned, survey_data, by.x = "id", by.y = "id")
```

# single ecdf

```{r}
person_id <- "03Nplw4GO2h5ut5"  # Sostituisci con l'ID della persona desiderata
covariate <- "danceability"  # Sostituisci con la covariata desiderata

# Seleziona le osservazioni per la persona specifica
person_data <- combined_data[combined_data$id == person_id, ]

# Funzione per creare un vettore di pesi esponenziali
create_exponential_weights <- function(n, alpha) {
  weights <- exp(-alpha * seq(0, n-1))
  return(weights)
}

# Calcola il numero di osservazioni
n <- nrow(person_data)

# Calcola i pesi esponenziali
alpha <- 0.1  # Puoi regolare il valore di alpha
weights_ecdf <- create_exponential_weights(n, alpha)

# Calcola l'EDF per la covariata specifica
edf <- spatstat.geom::ewcdf(person_data[[covariate]], weights = weights_ecdf, normalise = TRUE)

# Visualizza l'EDF
plot(edf, main = paste("EDF for", covariate, "for Person", person_id),
     xlab = covariate, ylab = "Empirical Probability")

```

#ecdf per una covariata musica

```{r}
# Esempio di calcolo della profondità della funzione per una covariata specifica
covariate <- "energy"  # Sostituisci con la covariata desiderata

# Creare una lista di EDF per tutte le persone
edf_list <- lapply(unique(combined_data$id), function(person_id) {
  person_data <- combined_data[combined_data$id == person_id, ]
  spatstat.geom::ewcdf(person_data[[covariate]], weights = weights_ecdf, normalise = TRUE)
})

plot(NULL, xlim = c(0, 1), ylim = c(0, 1),
     main = "Empirical Distribution Functions (EDF)",
     xlab = "Data Values", ylab = "Probability")

# Tracciare ogni EDF dalla lista
for (i in seq_along(edf_list)) {
  lines(edf_list[[i]], lwd = 0.5, cex = 0.1)
}
```

# auxiliarry functions

```{r}
grid <- seq(0, 1, length.out = 50)
create_edf_list <- function(music_cov){
  edf_list <-  lapply(unique(combined_data$id), function(person_id) {
    ecdf <- spatstat.geom::ewcdf(combined_data[combined_data$id == person_id,music_cov ],weights = weights_ecdf, normalise = TRUE)
    val = ecdf(grid)
    return(val)
  })
  return(edf_list)
}

create_indices_list <- function(unique_groups,survey_cov,median_curve_list){
  indices_list <- list()
  for (group in unique_groups) {
    indices <- which(survey_data[,survey_cov] == group)
    indices_list[[as.character(group)]] <- indices
  }
  return(indices_list)
}

plot_ecdf <- function(music_cov,survey_cov,edf_list,color_palette,median_curve_list){
  unique_groups = levels(as.factor(combined_data[,survey_cov]))
  plot(NULL, xlim = c(0, 1), ylim = c(0, 1),
  main = paste0(c("Empirical Distribution Functions (EDF) ",music_cov,"-",survey_cov)),
  xlab = "Data Values", ylab = "Probability")
  
  lapply(seq_along(edf_list), function(i) {
    group_value <- survey_data[i + 1, survey_cov]
    lines(grid, edf_list[[i]], lwd = 0.5, col = color_palette[unique_groups == group_value], cex = 0.1)
  })
  
  # Utilizza lapply e sapply per evitare il secondo ciclo for
  sapply(seq_along(unique_groups), function(i) {
    lines(grid, median_curve_list[[i]]$values, col = color_palette[i], lwd = 4)
  })
  legend("topleft", legend = unique_groups, col = color_palette, lwd = 2)
}


create_factors <- function(indices_list){
  length_list = length(unlist(indices_list))
  return_vect <- rep(0,length_list)
  for( g in 2:length(names(indices_list))){
    sub_group = indices_list[[g]]
    for(i in 1:length(sub_group))
      return_vect[sub_group[i]] = g-1
  }
  return(return_vect)
}


# Funzione per creare un vettore di pesi esponenziali
create_exponential_weights <- function(n, alpha) {
  weights <- exp(-alpha * seq(0, n-1))
  return(weights)
}

# Calcola il numero di osservazioni
n <- nrow(person_data)

# Calcola i pesi esponenziali
alpha <- 0.1  # Puoi regolare il valore di alpha
weights_ecdf <- create_exponential_weights(n, alpha)


```

# funzione "esternata" for debugging
```{r}
music_vars = colnames(data_numeric_cleaned)[1:13]
survey_covs = colnames(survey_data)[3:19]

ii = 8
jj = 1
music_cov = music_vars[[ii]]
survey_cov =  survey_covs[[jj]]
survey_cov = "abitanti.citta"
music_cov = "popularity"
# Creare una lista di EDF per tutte le persone
edf_list <- create_edf_list(music_cov)
matrice_da_lista_all <- do.call(cbind, edf_list)
f_data_all = fData(grid, t(matrice_da_lista_all))

# Definisci una palette di colori in base ai valori unici nella colonna di gruppo
unique_groups = levels(as.factor(combined_data[,survey_cov]))
num_groups <- length(unique_groups)
color_palette <- rainbow(num_groups)
indices_list <- create_indices_list(unique_groups,survey_cov)  


factor_aov_vect <- create_factors(indices_list)
response = t(matrice_da_lista_all)
resutl_aov = IWTaov(response ~factor_aov_vect)
pval = summary(resutl_aov)$factors[[1]]

if(pval<0.05)
  print(paste("found match", music_cov, survey_cov))


median_curve_list <- list()
relative_BD_list <- list()

for (i in 1:num_groups) {
  matrice_da_lista_i <- do.call(cbind, edf_list[indices_list[[i]]])
  f_data = fData(grid, t(matrice_da_lista_i))
  median_curve_list[[i]] <- median_fData(fData = f_data, type = "MBD")

  #relative depth function
  relative_BD_result <- BD_relative(median_curve_list[[i]], f_data_all)
  
  # Memorizza il risultato insieme al nome del gruppo
  relative_BD_list[[i]] <- list(group_name = unique_groups[i], result = relative_BD_result)
}
for (i in 1:num_groups)
  print(paste(paste("Group:", relative_BD_list[[i]]$group_name),relative_BD_list[[i]]$result))
plot_ecdf(music_cov,survey_cov,edf_list,color_palette,median_curve_list)

```

# depth function

```{r}
depth_covcov <- function(music_cov, survey_cov){ 
  
  # Creare una lista di EDF per tutte le persone
  edf_list <- create_edf_list(music_cov)
  matrice_da_lista_all <- do.call(cbind, edf_list)
  response = t(matrice_da_lista_all)
  f_data_all = fData(grid, response)
  
  # Definisci una palette di colori in base ai valori unici nella colonna di gruppo
  unique_groups = levels(as.factor(combined_data[,survey_cov]))
  num_groups <- length(unique_groups)
  color_palette <- rainbow(num_groups)
  indices_list <- create_indices_list(unique_groups,survey_cov)  
  
  factor_aov_vect <- create_factors(indices_list)
  
  resutl_aov = IWTaov(response ~ factor_aov_vect)
  pval = summary(resutl_aov)$factors[[1]]
  
  
  if(pval<0.05)
    return(c(music_cov,survey_cov))
  else
    return(0)


# median_curve_list <- list()
# relative_BD_list <- list()

# for (i in 1:num_groups) {
#   matrice_da_lista_i <- do.call(cbind, edf_list[indices_list[[i]]])
#   f_data = fData(grid, t(matrice_da_lista_i))
#   median_curve_list[[i]] <- median_fData(fData = f_data, type = "MBD")
# 
#   #relative depth function
#   relative_BD_result <- BD_relative(median_curve_list[[i]], f_data_all)
#   
#   # Memorizza il risultato insieme al nome del gruppo
#   relative_BD_list[[i]] <- list(group_name = unique_groups[i], result = relative_BD_result)
# }
# for (i in 1:num_groups)
#   print(paste(paste("Group:", relative_BD_list[[i]]$group_name),relative_BD_list[[i]]$result))
#plot_ecdf(music_cov,survey_cov,edf_list,color_palette,median_curve_list)

}
```

```{r}
depth_covcov("popularity","abitanti.citta"  )
```

# covariata persona fissata

```{r,warning=FALSE}
for(m in music_vars){
  depth_covcov(m,"libri")
}
```

# all music all survey covs

```{r,warning=FALSE}
music_vars = colnames(data_numeric_cleaned)[1:12]
music_vars = music_vars[!(music_vars %in% c("year","duration"))]
survey_covs = colnames(survey_data)[1:16]
survey_covs = survey_covs[!(survey_covs %in% c("genere"))]

results_aov = list()
k = 1
for(m in music_vars){
  #print(music_cov)
  for (s in survey_covs){
    #print(survey_cov)
    depth_covcov(m,s)
    results_aov[[k]] = depth_covcov(m,s)
    k = k+1
  }
}
print(results_aov)
```

```{r}
for (i in unique(missed_vars)){
  print(table(survey_data[,i]))
  print("------")
}
```

```{r}
ITPaovbspline(
  formula,
  order = 2,
  nknots = dim(model.response(model.frame(formula)))[2],
  B = 1000,
  method = "residuals"
)

ITPimage(ITP.result, alpha = 0.05, abscissa.range = c(0, 1), nlevel = 20)


```

```{r}
gruppi_lista <- list(
  malati = c(2, 5, 6, 7, 9, 13, 15, 17, 18, 20, 23, 27, 29, 30, 33, 34, 35, 36, 40, 41, 52, 54, 55, 56, 60, 63, 64, 69),
  sani = c(1, 3, 4, 8, 10, 11, 12, 14, 16, 19, 21, 22, 24, 25, 26, 28, 31, 32, 37, 38, 39, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 57, 58, 59, 61, 62, 65, 66, 67, 68)
)

```

```{r}
data(NASAtemp)
limit = 10
temperature <- rbind(NASAtemp$milan[,1:limit],NASAtemp$paris[,1:limit])
groups <- c(rep(0,22),rep(1,22))

# Performing the IWT
IWT.result <- IWTaov(temperature ~ groups,B=1000)

# Summary of the ITP results
summary(IWT.result)

# Plot of the IWT results

plot(IWT.result)

```
