---
title: "R Notebook"
output: html_notebook
---

```{r}
library(roahd)
library(fda)
```

## Loading numeric and survey data
```{r}
survey_data<-readRDS("../data/Surveycleaned.RData")
numeric_data<-readRDS("../data/data_numeric_cleaned2.RData")

combined_data <- merge(numeric_data, survey_data, by.x = "id", by.y = "id")
```
#standardize values 
*duration* and *year* in order to have consistent analysis
```{r}
min_max_normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}
  
combined_data$duration<-  min_max_normalize(combined_data[,12])
combined_data$year<-  min_max_normalize(combined_data[,13])
```

# fdata function 
```{r}
build_fData <- function(edf_list,graphics){
  # common x values
  my_set = c()
  for (ecd in edf_list){
    xx = environment(ecd)$x
    # Use the unique function to obtain unique elements
    my_set <- unique(c(xx,my_set))
  }
  x_axis = my_set[order(my_set)]

  functions <- list()
  k=1
  for (ecd in edf_list){
    functions[[k]] = list(x =environment(ecd)$x, y = environment(ecd)$y)
    k = k+1
  }
  
  # Function to extend each function to the common x values
  extend_function <- function(fn_list, common_x) {
    extended_functions <- lapply(fn_list, function(fn) {
      extended_y <- approx(x = fn$x, y = fn$y, 
                           xout = common_x, 
                           method = "constant", rule = 2)$y
      list(x = common_x, y = extended_y)
    })
    return(extended_functions)
  }
  
  # Extend each function to the common x values
  extended_functions <- extend_function(functions, x_axis)
  observation = c()
  for (k in 1:length(edf_list)){
   observation = rbind(observation,extended_functions[[k]]$y)
  }

  f_data = fData(x_axis,as.matrix(observation))
    if (graphics){
    plot(f_data)
  }
  return(f_data)
}
```




## Ecdf list per person

survey covariate


```{r}
col_survey = colnames(survey_data)[c(1:10,12:16)]
col_survey = colnames(survey_data)[c(1:3)]
names_cov<-colnames(combined_data)[2:13]

f_data_external_list <- list()

for (surv_cov in col_survey){
  levels_surv = levels(combined_data[,surv_cov])
  f_data_covariate_list = list()
  for (covariate in names_cov){
    f_data_lvl_list = list()
    
    for(lvl in levels_surv){
      temp_dataset =combined_data[ which(combined_data[,surv_cov]==lvl),]
      
        edf_list <- lapply(unique(temp_dataset$id), function(person_id) {
        person_data <- temp_dataset[temp_dataset$id == person_id, ]
        ecdf(person_data[[covariate]])
        })
        
      f_data = build_fData(edf_list, 0)
      f_data_lvl_list[[lvl]] = f_data 
    }
    f_data_covariate_list[[covariate]] <- f_data_lvl_list
    
  }
  f_data_external_list[[surv_cov]] <- f_data_covariate_list
}
```
```{r}
names(f_data_external_list$età$popularity)
```

# come funziona ecdf, extra
```{r}
person_data_year <- sort(combined_data[combined_data$id == unique(combined_data$id)[1],"year" ])
ex = edf_list[[1]]
unique(person_data_year) == environment(ex)$x
ex = edf_list[[1]]
#summary.stepfun(ex)
environment(ex)$x
environment(ex)$y

f_data = fData(environment(ex)$x, environment(ex)$y)
plot(f_data)
```






