---
title: "Tancredi"
output: html_document
date: "2023-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#library
```{r}
source("preprocess_numeric.R")
source("normalize_numeric.R")
source("normalize_numeric_global.R")
library(ggplot2)
```

# Load Datasets
```{r}
dataset_list = readRDS("../data/data_list.RData")
names(dataset_list)
dataset_list[[1]]
```

#Preprocessing
```{r}
# this chunk provides numeric data normalized in a global way
# option2 
numeric_list <- list()
for (i in seq_along(dataset_list)) {
  data <- dataset_list[[i]]
  numeric_list[[i]] <- data[, c(5, 7:15, 18, 19)]
}
numeric_list <- normalize_numeric_global(numeric_list)

combined_numeric <- do.call(rbind, numeric_list)

#combined_numeric
```


```{r}
#LOCAL BOXPLOT
#use this to have a boxplot of the variables you want to visualize
#change this line with the number of the numeric dataset you want to open
#numeric<-numeric_list[[1]]


numeric<-numeric_list[[2]]
col_names<-colnames(numeric)
boxplot(numeric[,1:10], col = "lightblue", main = "Boxplots", names = col_names[1:10], cex.axis = 0.5)
par(mfrow = c(1, 2))
boxplot(numeric[,11], col = "lightblue", main = "Duration", names = col_names[11], cex.axis = 0.5)
boxplot(numeric[,12], col = "lightblue", main = "Year", names = col_names[12], cex.axis = 0.5)

```

```{r}
#GLOBAL BOXPLOTS
col_names<-colnames(combined_numeric)
boxplot(combined_numeric[,1:10], col = "lightblue", main = "Boxplots", names = col_names[1:10], cex.axis = 0.5)
par(mfrow = c(1, 2))
boxplot(combined_numeric[,11], col = "lightblue", main = "Duration", names = col_names[11], cex.axis = 0.5)
boxplot(combined_numeric[,12], col = "lightblue", main = "Year", names = col_names[12], cex.axis = 0.5)
```
```{r}
# POSSO ELIMINARE INSTRUMENTALNESS?
#var(combined_numeric[["instrumentalness"]])
#decido di eliminarla (veder anche pca di ale a proposito)
#elimino anche liveness perchè non mi da informazioni utili (dataset composto quasi solo da musica registrata in studio e anche se così non fosse mi importa poco)
new_list <- list()
for (i in seq_along(dataset_list)) {
  data <- numeric_list[[i]]
  new_list[[i]] <- data[, c(1:4,7:12)]
}

combined_numeric <- do.call(rbind, new_list)

combined_numeric
```

#PCA
```{r}
#faccio pca sul datset globale
temp_list <- list()
for (i in seq_along(dataset_list)) {
  data <- dataset_list[[i]]
  temp_list[[i]] <- data[, c(5, 7:10, 13:15, 18, 19)]
}
temp_data <- do.call(rbind, temp_list)
scaled_data <- scale(temp_data)
pc.data <- princomp(scaled_data, scores=T)
summary(pc.data)

load.data <- pc.data$loadings
par(mfrow = c(3,1))
for(i in 1:3) barplot(load.data[,i], ylim = c(-1, 1), main = paste('PC', i))
load.data

#pca inutiule
```
#Riassumo i dati con media e varianza
```{r}
result_list <- list()
for (i in seq_along(dataset_list)) {
  result_list[[i]] <- preprocess_numeric( numeric_list[[i]], DataFrameID = i)
}

#potrebbe esseci un errore visto che prendo in input numeric_list che è gia stata scalata. inoltre ci sono tutte le colonne

final_result_df <- do.call(rbind, result_list)
final_result_df$Value <- round(final_result_df$Value, 3)
view(final_result_df)
```
#Guardo le categoriche
```{r}
#factor list containing for each element a dataframe of factors
factor_list <- list()
for (i in seq_along(dataset_list)) {
  data <- dataset_list[[i]]
  factor_list[[i]] <- data[,c(2,3,4,6,16,17,20:ncol(data))]
}
combined_factor <- do.call(rbind, factor_list) #non funziona perchè giustamente ogni playlist ha un numeri duverso di colonne 
head(combined_factor)
#come riassumere i generi? ecco alcune proposte 
#https://www.analyticsvidhya.com/blog/2021/06/music-genres-classification-using-deep-learning-techniques/


#altra proposta di ripartizione generi (forse la migliore)
'''Pop: Encompassing popular and mainstream music that appeals to a wide audience. Pop music often incorporates elements from various genres.

Rock: A broad category that includes various rock subgenres such as classic rock, alternative rock, indie rock, and more.

Electronic/Dance: Encompassing electronic music genres such as techno, house, trance, dubstep, and more.

Hip-Hop/Rap: Incorporating hip-hop and rap genres, including subgenres like trap, old school hip-hop, and experimental hip-hop.

Country: Encompassing various styles of country music, from traditional country to country pop.

Jazz: Covering a wide range of jazz styles, including traditional jazz, swing, bebop, and modern jazz.

Classical: Including classical music compositions from different periods, such as Baroque, Classical, Romantic, and Contemporary classical.

World/Folk: Encompassing music from various cultural traditions, folk music, and world music genres.

R&B/Soul: Incorporating rhythm and blues, soul, and related genres.

Metal: A category that includes various metal subgenres, such as heavy metal, thrash metal, death metal, and more.'''
```


